steps:
  - name: guergeiro/pnpm:current-8
    entrypoint: pnpm
    args: [ 'install' ]
  - name: guergeiro/pnpm:current-8
    entrypoint: pnpm
    args: [ '--filter', '@symphco/mecha-kucha-common', 'build' ]
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: /bin/bash
    args: [ '-c', 'printenv > .env' ]
    dir: 'packages/frontend'
    env:
      - 'NEXT_PUBLIC_BACKEND_BASE_URL=${_NEXT_PUBLIC_BACKEND_BASE_URL}'
      - 'PORT=${_PORT}'
  - name: guergeiro/pnpm:current-8
    entrypoint: pnpm
    args: [ '--filter', '@symphco/mecha-kucha-frontend', 'build' ]
  - name: guergeiro/pnpm:current-8
    entrypoint: pnpm
    args: [ '--filter', '@symphco/mecha-kucha-frontend', 'cloudbuild-pack' ]
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [ 'app', 'deploy', 'app.yaml' ]
    dir: 'packages/frontend/.cloudbuild'
timeout: 1800s
