runtime: nodejs20
service: default

instance_class: F1
inbound_services:
  - warmup

automatic_scaling:
  min_idle_instances: 1

handlers:
  - url: /_ah/warmup
    script: auto
  - url: /.*
    secure: always
    script: auto
