steps:
  - name: guergeiro/pnpm:current-8
    entrypoint: pnpm
    args: [ 'install' ]
  - name: guergeiro/pnpm:current-8
    entrypoint: pnpm
    args: [ '--filter', '@symphco/mecha-kucha-common', 'build' ]
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: /bin/bash
    args: [ '-c', 'printenv > .env' ]
    dir: 'packages/backend'
    env:
      - 'GOOGLE_CLOUD_OAUTH2_BASE_URL=${_GOOGLE_CLOUD_OAUTH2_BASE_URL}'
      - 'GOOGLE_CLOUD_OAUTH2_ENDPOINT=${_GOOGLE_CLOUD_OAUTH2_ENDPOINT}'
      - 'GOOGLE_CLOUD_OAUTH2_CLIENT_ID=${_GOOGLE_CLOUD_OAUTH2_CLIENT_ID}'
      - 'GOOGLE_CLOUD_OAUTH2_CLIENT_SECRET=${_GOOGLE_CLOUD_OAUTH2_CLIENT_SECRET}'
      - 'GOOGLE_CLOUD_OAUTH2_TOKEN_BASE_URL=${_GOOGLE_CLOUD_OAUTH2_TOKEN_BASE_URL}'
      - 'GOOGLE_CLOUD_OAUTH2_TOKEN_ENDPOINT=${_GOOGLE_CLOUD_OAUTH2_TOKEN_ENDPOINT}'
      - 'UNSPLASH_API_BASE_URL=${_UNSPLASH_API_BASE_URL}'
      - 'UNSPLASH_API_ENDPOINT=${_UNSPLASH_API_ENDPOINT}'
      - 'UNSPLASH_API_CLIENT_ID=${_UNSPLASH_API_CLIENT_ID}'
      - 'UNSPLASH_API_CLIENT_SECRET=${_UNSPLASH_API_CLIENT_SECRET}'
      - 'AIROPS_API_BASE_URL=${_AIROPS_API_BASE_URL}'
      - 'AIROPS_API_ENDPOINT=${_AIROPS_API_ENDPOINT}'
      - 'AIROPS_API_ACCESS_TOKEN=${_AIROPS_API_ACCESS_TOKEN}'
      - 'AIROPS_API_ACCESS_TOKEN_TYPE=${_AIROPS_API_ACCESS_TOKEN_TYPE}'
      - 'GOOGLE_SLIDES_API_BASE_URL=${_GOOGLE_SLIDES_API_BASE_URL}'
      - 'GOOGLE_SLIDES_API_PRESENTATIONS_ENDPOINT=${_GOOGLE_SLIDES_API_PRESENTATIONS_ENDPOINT}'
      - 'FRONTEND_BASE_URL=${_FRONTEND_BASE_URL}'
      - 'PORT=${_PORT}'
  - name: guergeiro/pnpm:current-8
    entrypoint: pnpm
    args: [ '--filter', '@symphco/mecha-kucha-backend', 'build' ]
    dir: 'packages/backend'
  - name: guergeiro/pnpm:current-8
    entrypoint: pnpm
    args: [ '--filter', '@symphco/mecha-kucha-backend', 'cloudbuild-pack' ]
    dir: 'packages/backend'
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [ 'app', 'deploy', 'app.yaml' ]
    dir: 'packages/backend/.cloudbuild'
timeout: 1800s
